### ISSUE TITLE
Fix summarise error

### ISSUE THREAD

**Issue by DannyDakota** [AY2122S2-CS2103T-T12-3/tp#123]
With the original addressbook, using the summarise function gives the following screenshot.
![Screenshot 2022-03-29 at 1 47 12 AM](https://user-images.githubusercontent.com/51451719/160456802-25522754-760e-4639-b5b0-52a7919f2521.png)

However, after inputting "delete 6", referring to Roy from Block E who is the only one in the sample data that is from block E.
![Screenshot 2022-03-29 at 1 48 31 AM](https://user-images.githubusercontent.com/51451719/160457004-3c85bb36-a4f1-40d3-ba14-fe11b64d6fe1.png)

The piechart is not updated and the piechart for block E is still reflected as Roy being present
![Screenshot 2022-03-29 at 1 48 49 AM](https://user-images.githubusercontent.com/51451719/160457045-77b8abe7-9cfa-4916-9a89-71dd48cd25e5.png)

**Comment by jiale-c** [comment]
Fixed with a recent PR #126.
