### ISSUE TITLE
[PE-D] Broken Link in Delete Command Documentation

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T12-3/tp#181]
## Summary

The link to the `find` command in the documentation for the `delete` command is broken in the User Guide.

## Screenshot of UG

![image.png](https://raw.githubusercontent.com/sharpstorm/ped/main/files/6c6b7536-3bc0-42cf-b5d9-977e806b9ed8.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: sharpstorm/ped#10

**Comment by cwq2326** [comment]
done
