### ISSUE TITLE
[PE-D] Import does not work

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T12-3/tp#185]
![Screenshot 2022-04-01 145723.png](https://raw.githubusercontent.com/fantablack/ped/main/files/a66e1041-db6e-411b-9a32-3608db54960f.png)

Steps to replicate:
1. Create an Excel Sheet with the same values structure as the referenced screenshot. (Followed from Sample Excel in UG, including typo of Facaulty)
2. Click Import

Actual Outcome:
* Nothing happens. No indication of failure or success in the GUI.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: fantablack/ped#4

**Comment by kevinkuo0320** [comment]
The column name needs to be capitalized, which I have updated inside the User Guide
