### ISSUE TITLE
[PE-D] Section on Viewing Help in User Guide is Incoherent

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T12-3/tp#217]
## Summary

The `viewing help` section in the user guide has a text and screenshot that is inconsistent. The text mentions `list` but the screenshot shows `find`.

**Screenshot of Current State**

![image.png](https://raw.githubusercontent.com/sharpstorm/ped/main/files/7df00fbe-90f2-499c-8ed6-c6119b2e3d62.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: sharpstorm/ped#28

**Comment by cwq2326** [comment]
done
