### ISSUE TITLE
 Do a trial JAR release

### ISSUE THREAD

**Issue by cwq2326** [AY2122S2-CS2103T-T12-3/tp#78]
* Do a product release [as described in the Developer Guide](https://nus-cs2103-ay2122s2.github.io/tp/DevOps.html#making-a-release). You can name it something like v1.2.1 (or v1.3.trial). Ensure that the jar file works as expected in an empty folder and using Java 11, by doing some manual testing. Reason: You are required to do a proper product release for v1.3. Doing a trial at this point will help you iron out any problems in advance. It may take additional effort to get the jar working especially if you use third party libraries or additional assets such as images.
* If you want to smoke-test your JAR file on an OS that is not available within your team, you can post a request in the forum to see if anyone else in the class can help you smoke-test it on that OS.

Click [here](https://nus-cs2103-ay2122s2.github.io/website/schedule/week10/project.html#6-do-a-trial-jar-release) for more details.

**Comment by jiale-c** [comment]
Jar file is present in our team repository
